mvnScalaTest:
  image: maven:3.5.0-jdk-8
  stage: test
  script:
    - export MAVEN_OPTS="-Dmaven.repo.local=$(pwd)/mvn-cache" # must be an absolute path for maven
    - mvn test
  cache:
    key: "mvn-$CI_BUILD_REF_NAME" # contains either the branch or the tag, so it's caching per branch
    paths:
    - mvn-cache
    - target # might need to use mvn clean test for slower but more reproducible builds

sbtScalaTest:
  image: 1science/sbt:0.13-oracle-jdk-8
  stage: test
  script:
  - sbt test
  cache:
    key: "sbt-$CI_BUILD_REF_NAME" # contains either the branch or the tag, so it's caching per branch
    paths:
    - sbt-cache
    - target # might need to use sbt clean test for slower but more reproducible builds
  variables:
    SBT_OPTS: "-Dsbt.global.base=sbt-cache/sbtboot -Dsbt.boot.directory=sbt-cache/boot -Dsbt.ivy.home=sbt-cache/ivy"
    COURSIER_CACHE: "sbt-cache/coursier"
