mvtScalaTest:
  image: maven:3.5.0-jdk-8
  stage: test
  script:
    - mvn test
  cache:
    paths:
      - ~/.ivy2/cache

sbtScalaTest:
  image: hseeberger/scala-sbt
  stage: test
  script:
  - sbt test
  cache:
    paths:
      - ~/.m2/repository
