mvtScalaTest:
  image: maven:3.5.0-jdk-8
  stage: test
  script:
    - mvn test
  cache:
    paths:
      - ~/.ivy2/cache

sbtScalaTest:
  image: hseeberger/scala-sbt
  stage: test
  script:
  - sbt test
  cache:
    key: "$CI_BUILD_REF_NAME" # contains either the branch or the tag, so it's caching per branch
    paths:
    - "sbt-cache/.ivy.cache"
    - "sbt-cache/.boot"
    - "sbt-cache/.sbtboot"
    - "sbt-cache/target"  
  variables:
    SBT_OPTS: "-Dsbt.global.base=sbt-cache/.sbtboot -Dsbt.boot.directory=sbt-cache/.boot -Dsbt.ivy.home=sbt-cache/.ivy"
