# use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.ivy2/cache

language: scala

jdk:
  - oraclejdk8

scala:
  - 2.12.4

script:
  - mvn test
  - sbt test

notifications:
  email:
    - michel@daviot.info
