# use Docker-based container (instead of OpenVZ)
sudo: false

language: scala

jdk:
  - oraclejdk8

scala:
  - 2.12.4

script:
  - sbt test
  - MAVEN_OPTS="-Dmaven.repo.local=$(pwd)/mvn-cache" bash -c 'mvn test' 
  # maven.repo.local must be an absolute path 

notifications:
  email:
    - michel@daviot.info

env:
  global:
    - SBT_OPTS="-Dsbt.global.base=sbt-cache/sbtboot -Dsbt.boot.directory=sbt-cache/boot -Dsbt.ivy.home=sbt-cache/ivy"
    - COURSIER_CACHE="sbt-cache/coursier"

cache:
  directories:
    - sbt-cache
    - mvn-cache
