# use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.m2/repository # maven
    - $HOME/.ivy2/cache # sbt
    - $HOME/.sbt/launchers # sbt
    - $HOME/.coursier/cache # sbt + coursier

language: scala

scala:
  - 2.13.0

script:
  - mvn test
  - sbt test

notifications:
  email:
    - michel@daviot.info
